# Generated by Django 2.2.1 on 2019-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(verbose_name='통화 단위당 가격'),
        ),
    ]
