# Generated by Django 2.2.1 on 2019-06-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20190605_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='기업 로고'),
            preserve_default=False,
        ),
    ]
