# Generated by Django 2.2.1 on 2019-06-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='image',
        ),
    ]
