# Generated by Django 2.2.1 on 2019-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(verbose_name='통화단위당 가격'),
        ),
    ]
